apiVersion: v1
kind: Service
metadata:
  name: cluster-version-operator
  namespace: openshift-cluster-version
  labels:
    k8s-app: cluster-version-operator
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: cluster-version-operator-serving-cert
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  type: ClusterIP
  selector:
    k8s-app: cluster-version-operator
  ports:
  - name: metrics
    port: 9099 # chosen to be in the internal open range
